### ISSUE TITLE
Purify not pruning the css file

### ISSUE THREAD

**Issue by Risto-Stevcev** [purifycss/purifycss#116]
**index.html**
```html
<html>
  <body>
    <h1>Foo</h1>
    <span id="bar">Bar</span>
    <b>Baz</b>
  </body>
</html>
```

**style.css**
```css
body {
    background-color: #000;
    color: #fff;
}

span#foo { font-weight: bold; }
span#bar {  color: blue; }
p {  color: red; }
```

In this case, it will prune `p`, but it will not prune `span#bar`, even though nothing in the html matches that selector

**Comment by Illyism** [comment]
You mean `span#foo` should be deleted, right?

**Comment by Risto-Stevcev** [comment]
Yeah

**Comment by nojaf** [comment]
I have something similar

**index.html**:
```html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<h1>Purify</h1>
</body>
</html>
```

**style.css**:
```css
body{
	margin:0 25em;
	background: #ccc;
	color:#020202;
	font-family: 'Segoe UI','Arial';
}

h1{
	color:#F2F2F2;
}

h2{
	color:red;
}
```

Expected outcome is that the h2 is gone.
But nothing was removed.

**package.json**:
```json
{
  "name": "purifycss-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "purify":"purifycss style.css './index.html' --info --out style-pure.css"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "purifycss": "^1.1.9"
  }
}

```
