### ISSUE TITLE
Tool removes @font-face declarations :(

### ISSUE THREAD

**Issue by mike3run** [purifycss/purifycss#151]
Is there a way to prevent that? For everything else works great just my @font-face declarations are stripped away from the end-result :(

Maybe a way to filter them?

Thanks a lot

**Comment by bebraw** [comment]
Can you give an example of a rule it removes? I wonder if whitelisting would fix it. It may require a source change too.

**Comment by mike3run** [comment]
Sure thing. I've noted it removes all of the `@font-face` declarations (for custom fonts)

Input:
```css
@font-face
{
    font-family: 'Cerebri Sans';
    font-weight: 400;
    font-style: normal;

    src: url('../fonts/CerebriSans-Regular.eot?') format('eot'), url('../fonts/CerebriSans-Regular.otf') format('opentype'), url('../fonts/CerebriSans-Regular.svg#Cerebri_Sans') format('svg'), url('../fonts/CerebriSans-Regular.ttf') format('truetype'), url('../fonts/CerebriSans-Regular.woff') format('woff');
}
```

Output
```css
// Nothing to see here
```
