### ISSUE TITLE
Helper classes with similar names are not removed

### ISSUE THREAD

**Issue by jsnanigans** [purifycss/purifycss#189]
Here is a very simple example that shows my problem:
```javascript
var purifyCss = require("purify-css")

var html = '<div class="span-2"></div>'
var css = `
/* only .span-2 should stay */
.span-1 {width: 1vw} 
.span-2 {width: 2vw} 
.span-3 {width: 3vw}

/* .extra will be removed */
.extra {width: 100vw}
`

var purified = purifyCss(html, css, {})
```

the output I get is this:

```css
/* only .span-2 should stay */
.span-1 {
  width: 1vw;
}
.span-2 {
  width: 2vw;
}
.span-3 {
  width: 3vw;
}
/* .extra will be removed */
```

you can try this for yourself here: https://runkit.com/jsnanigans/5a01849baa30e50011c511e7

### To summarize;
The classes `span-1 span-2 span-3` exist in the original css, but in my html I only use `span-2`. I would expect `span-1` and `span-3` to be removed but they persist in the purified output.

I can't imagine that I am the first to notice this, so I apologize if this is a re post.
