### ISSUE TITLE
Doesn't work with camelcase names

### ISSUE THREAD

**Issue by ankitshah2787** [purifycss/purifycss#30]
This works and keeps `#test` intact. 
```html
<div id='test'></div>
```
```css
#test {
    position: absolute;
}
```

But this doesn't, it removes `#testFoo` from css

```html
<div id='testFoo'></div>
```
```css
#testFoo {
    position: absolute;
}
```
