### ISSUE TITLE
Add Support for Pseudo Elements

### ISSUE THREAD

**Issue by Illyism** [purifycss/purifycss#39]
Add support for [Pseudo Elements](http://www.w3.org/TR/css-pseudo-4/).
All of these should still be available after purification.

```css
*,
::before,
::after {
	background: black;
}

::selection {
	background: black;
}

::-webkit-scrollbar {
	background: black;
}

::-webkit-scrollbar:vertical {
	background: black;
}
```
