### ISSUE TITLE
Some CSS rules in media queries are being ignored 

### ISSUE THREAD

**Issue by JMPerez** [purifycss/purifycss#52]
I am trying to apply `purifycss` to some stylesheets based on Bootstrap. I have realized that, in some cases, rules within media queries are ignored.

Given this HTML:
```html
<!doctype html>
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <div class="col-md-9">
        HI
    </div>
</body>
</html>
```

and this stylesheet:

```css
@media (min-width: 768px) {
  .col-md-9, .col-md-10 {
    float: left;
  }
}

.col-md-9 {
  background-color: red;
}
```

the output after passing it through `purifycss` is:

```css
.col-md-9 {
  background-color: red;
}
```

However, some similar snippets do work as expected. For instance:

```css
@media (min-width: 768px) {
  .col-md-9 {
    float: left;
  }
}

.col-md-9 {
  background-color: red;
}
```

and so does

```css
.col-md-9, .col-md-10 {
  float: left;
}

.col-md-9 {
  background-color: red;
}
```

You can try this if in your `test/test_examples/media_queries/media_queries.css` you replace the contents with

```css
@media (max-width: 600px) {
  div.media-class {
    color: black;
  }

  div.media-class, .col-md-10 {
    float: left;
  }

  .alone {
    color: black;
  }

  #id-in-media {
    color: black;
  }

  body {
    color: black;
  }
}

@media (max-width: 960px){
  .unused-class {
    color: black;
  }
}
```

and print out the `result` of the test in `test/purify_test.js`.
