### ISSUE TITLE
Escaped class names are being removed

### ISSUE THREAD

**Issue by ocReaper** [purifycss/purifycss#54]
Hi!
I'm using a pretty neat styling convention for CSS, the: http://www.csstyle.io/
The problem is, for this HTML:
```html
<span class="@home">
  <a class="button --action +rounded +glass">
    Register Now
    <span class="button__icon --rocket"></span>
  </a>
</span>
```
I have this CSS:
```css
.\@home .button {
  background: #6BD9ED;
  padding: 15px;
}
.\@home .button.\--action {
  color: #1F1F1F;
  background: #A7E040;
}
.\@home .button.\+rounded {
  border-radius: 10px;
}
.\@home .button.\+glass {
  box-shadow: inset 0 0 6px rgba(0,0,0,.8), 
              inset 0 9px 1px rgba(0,0,0,.1);
}
.\@home .button__icon {
    font-size: 34px;
    position: relative;
    top: 10px;
}
.\@home .button__icon.\--rocket:before {
    content: "\e600";
}
```
And it does not match in purifycss due to the escapings in CSS.
